[package]
name = "rust_jwt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
chrono = "0.4.26"
jsonwebtoken = "8.3.0"
serde = { version = "1.0.182", features = ["derive"] }
